### ISSUE TITLE
pip installation misses dependencies

### ISSUE THREAD

**Issue by rhaleblian** [idlesign/steampak#2]
Thanks for sharing steampak.
It looks like at least bs4 and click are dependencies, and pip was skipping them.
I've never pushed anything to PyPI, but the attached patch worked when making a local editable install with pip.

[patch-install_requires.txt](https://github.com/idlesign/steampak/files/818722/patch-install_requires.txt)

This was created using
```shell
git diff -p
```

-ray

**Comment by idlesign** [comment]
You're welcome.

It's not an option to make this ``install_requires`` since steampak only needs those to work with Web API but not for ``libsteam``. Yet we can certainly put them into ``extras_require`` and update the docs and ``INSTALL`` file.

So you're welcome to fork, improve and pull request.

**Comment by rhaleblian** [comment]
Ah, very good.
